### ISSUE TITLE
Modifications for Path State Figure in Section 4.2

### ISSUE THREAD

**Issue by Yanmei-Liu** [quicwg/multipath#112]
In Section 4.3 [Path States](https://quicwg.org/multipath/draft-ietf-quic-multipath.html#name-path-states) we wrote:
```
       o
       | PATH_CHALLENGE sent/received on new path
       v
 +------------+    Path validation abandoned
 | Validating |----------------------------------+
 +------------+                                  |
       |                                         |
       | PATH_RESPONSE received                  |
       |                                         |
       v        Associated CID have been retired |
 +------------+        Path's idle timeout       |
 |   Active   |----------------------------------+
 +------------+                                  |
       |                                         |
       | PATH_ABANDONED sent/received            |
       v                                         |
 +------------+                                  |
 |   Closing  |                                  |
 +------------+                                  |
       |                                         |
       | Associated CID have been retired        |
       | Path's idle timeout                     |
       v                                         |
 +------------+                                  |
 |   Closed   |<---------------------------------+
 +------------+

```

There are 2 problems in this figure:
1. "Associated CID have been retired" should not cause the path turn into closed state, because in Section [4.2.2. ](https://quicwg.org/multipath/draft-ietf-quic-multipath.html#section-4.2.2)[Effect of RETIRE_CONNECTION_ID Frame](https://quicwg.org/multipath/draft-ietf-quic-multipath.html#name-effect-of-retire_connection) :

> Receiving a RETIRE_CONNECTION_ID frame causes the endpoint to discard the resources associated with that connection ID. If the connection ID was used by the peer to identify a path from the peer to this endpoint, the resources include the list of received packets used to send acknowledgements. The peer MAY decide to keep sending data using the same IP addresses and UDP ports previously associated with the connection ID, but MUST use a different connection ID when doing so.

  So retiring associated CID only cause the resources belonging to the corresponding packet number space to be released, but not the whole path to be closed. In CID migration cases, endpoints just want to retire the old CID and use a new one, as path is defined as "refers to the 4-tuple"  in the current draft, this operation will not cause the whole path context (including congestion control states, RTT measurements, etc.) to be removed.

2. Path closing is triggered by PATH_ABANDONED frame, and does not have dependency on CID retiring (Although path closing would trigger the retirement of CID resource). So when path_state transmit from "Closing" to "Closed", the proper condition might be "Acknowledgement of PATH_ABANDONED frame received" or "Path's draining timeout for at least 3 times the current PTO interval".

**Comment by yfmascgy** [comment]
First, regarding the transitioning from a "closing" state to a "closed" state, there will be a problem if we use the receipt of the ACK of a PATH_ABANDON as a condition for the transitioning due to possible out-of-order delivery. Suppose a client uses DCID S2 to on its first path to send three pkts with the packet number 100, 101, and 102, where PATH_ABANDON frame is sent in packet 102. However, due to the out-of-order delivery, it is possible that 102 is acked first, while packet 100 and 101 are still in flight. Therefore, at this point, we cannot mark the first path as "closed" since it is also possible that the acks of those two packets will later return from the first path. Due to the above reasons, in the initial design, we say that the path should be closed after CIDs are retired. As shown in the path-closing figure (Fig.3) in the draft, after the client makes sure that the packets (100, 101) sent before PATH_ABANDON on path 1 are also acknowledged, it then decides that the CID S2 is no longer needed, and thus sending out the RETIRE_CONNECTION_ID frame.

Second, regarding the transitioning from an "active" state to a "closed" state, yes, it is possible that we want to retire the old CID and use a new one, and I think the current figure is a bit confusing.  The purpose of this transitioning is to handle exceptions and it basically says that when there are no available CIDs to use for communication on a particular path, we should close it. I think we can simply keep the "path's timeout" as the condition because when there are no available CIDs, the path timeout will be triggered anyway.

**Comment by qdeconinck** [comment]
I agree that the transitioning from "Active" to "Closed" should not be directly done if we retire the associated CID. We could instead have an intermediate "Idle" state in which as long as you have no associated CID, keep relevant recovery/RTT/... contexts.

In general, I think it could be worthwhile to make a clearer distinction between the acknowledgment/packet number context and the recovery one. For instance, if for any reason a host changes the DCID used over a given path, it should still keeps track of packets sent with the previous DCID (and thus possibly sent with a different packet number space).

For the "Closing" to "Closed" transition, I tend to agree with Yunfei and I would not directly rely on the acknowledgment of the PATH_ABANDON frame to close my path. But as a sender, I can react to the acknowledgment of my PATH_ABANDON frame and send the RETIRE_CONNECTION_ID frame. On the other hand, relying on 3*PTO to transition from "Closing" to "Closed" is probably more relevant than using the path's idle timeout.

**Comment by mirjak** [comment]
@Yanmei-Liu your PR (#116) says 

> Note that if a path became idle timeout, endpoints SHOULD send PATH_ABANDONED frame before closing the path.

While you wrote in your comment above that it might be useless to send PATH_ABANDONED. Am I missing something?
