### ISSUE TITLE
Do we really need the PNS ID? And what happens when the connection ID changes on a single path?

### ISSUE THREAD

**Issue by mirjak** [quicwg/multipath#150]
If the connection ID is changed but the 5-tuple stays the same, the path ID changes as well but the packet number space ID sticks with the old/initial value and can be identified based on the 5 tuple. Is that correct? If so we should explain that somewhere.

Alternatively, do we really need both a path ID and the PNS ID? Even for the single packet number space, you can simply use the normal ACK frame and therefore would not need the PNS ID.

**Comment by qdeconinck** [comment]
Currently, from my understanding, if the CID changes over a path, then both the path ID and the packet number space (ID) change as well, given that you map the packet number space with the CID used. Also, if for some reason a passive migration (e.g. NAT rebinding) happens when changing the CID, the 5-tuple would change from the peer's viewpoint and I'm not sure how your mechanism's understanding would work there.

Regarding the path ID and the PNS ID, IIRC we initially wanted to keep the door open to different path IDs and PNS IDs. Now, I'm not sure we want to use something else than the CID (sequence number) and if we simplify the draft to only describe the situation with non-zero length CIDs, we may get rid of these notions.

**Comment by mirjak** [comment]
Okay, we need to more clear in the draft what's updated when. Because that wasn't clear to me.

If we go for SPNS, we should consider removing the difference. If we keep both, we might need slightly more clarification of why both are needed.

But let's wait with this issue until we decided about SPNS.

**Comment by mirjak** [comment]
Opened #169 instead
