### ISSUE TITLE
Clarification on Path Migration in relation to opening a new path

### ISSUE THREAD

**Issue by gloinul** [quicwg/multipath#458]
Path Migration for the case when the client is not aware of the change, like for NAT address rebinding case can't be avoided. Thus, this needs to be supported by server as something that can occur. However, if a client have a new address it could technically select to migrate an existing path to this new path. However, it appears more suitable to have a very strong recommendation here to actually open a new path in these cases. Combined possibly with abandoning another existing path. 

This issue is based on the interop testing.

**Comment by huitema** [comment]
The more I think about it, the more I believe that we should not try to support the "path migration" scenario. Currently, we have a very deterministic logic:

- identify the path by the path ID of the incoming packet.
- if the path ID was not seen yet, this is a new path.
- if the path ID exists already:
- if the 4 tuple match, and the CID match, no problem.
- if the CID is new, rotate the local CID
- if the 4 tuple does not match, treat that has a NAT traversal, challenge the old and the new address, retains the one for which the challenge works.

The "path migration" scenario breaks that logic. The CID is new, but it should not be rotated. Traffic should continue with the old CID, as in classic 9000. The server should only try to validate the new 4-tuple, not the old one. We have to reintroduce the concept of path-validating frames. We have to distinguish between NAT rebinding an migration by checking whether the CID is new, but we selected the unique-path-id architecture precisely because we know we cannot do that reliably.

Instead of attempting path migration of an existing path, applications have a much better solution: just create a new path with the new 4 tuple, and then abandon the old path after validating the new one. This gives us a safe migration.

During the interop testing, picoquic was reacting poorly to the migration attempt. I think I fixed that by simply ignoring any path challenge received on a different 4 tuple on an existing path. That means falling back to the NAT traversal code if someone attempts a "path migration". It will probably move the confusion to the implementation that is attempting these migrations, which I believe is fair since they should not be doing that in the first place.

**Comment by huitema** [comment]
There is a related issue with handling of the server preferred address, see issue #460.

**Comment by mirjak** [comment]
@huitema can you explain the problem in the case where you receive a packet with a new CID on a new tuple for an in-use path ID. This case is not special and should simply work inline with path migration as specified in RFC9000. Of course we should recommend to open a new path instead but it should like you think there is an actual problem here that needs fixing and it's not clear to me what exactly the problem is...?

**Comment by Yanmei-Liu** [comment]
In the current draft, when endpoint receive a new packet, it decides with the packet DCID:
- Different path ID, same / different 4-tuple, using a different path
- Same path ID, same 4-tuple, using the same path
        - New CID, CID rotation on the same path
- Same path ID, different 4-tuple, NAT-rebinding or migration
        - Same CID, NAT-rebinding
        - New CID, Path Migration

My opinion is that whether choose to create a new path or using path migration, it depends on the endpoint want 2 paths at the same time or not. Further more, it depends on whether the endpoint want to send packets with 2 different address at the same time or not.
If it only wants to use one path at the same time, but still wants to continuesly sending packets through different address, path migration would be a good choice.

**Comment by huitema** [comment]
Look at the [minutes of QUIC for IETF 118](https://notes.ietf.org/notes-ietf-118-quic#). we had a long discussion of precisely 'simultaneous rebinding + CID rotation', that was one of the key arguments for moving to the "unique path id" design. See also the old issue #188.

The problem is that there are four possible events:  CID rotation, NAT rebinding, NAT rebinding with simultaneous CID rotation, and migration. I wrote a summary of scenario in the following table, in which:

* Observation is what the peer sees: CID, which in all cases  point to the same path ID, and 4-tuple
* Whether verification is needed or not.
* What to do if verification fails.

The results for the peer are:

Event | Observation | Verification needed | If verification fails
-------|--------------|-----------------------|----------
CID rotation | Different CID, same 4-tuple | No | Cannot fail
NAT rebinding | Same CID, same 4-tuple | Yes | retain old 4 tuple
NAT rebinding with simultaneous CID rotation | Different CID, different 4-tuple | Yes | retain old 4 tuple, use new CID
Migration | Different CID, different 4-tuple | Yes | retain old 4 tuple, use old CID (per RFC 9000). In case of success, wait for validating frames before using the new 4-tuple

In various discussions, we pointed out that NAT rebinding with simultaneous CID rotation is actually a frequent case. Suppose that there is a gap in traffic, a few seconds of silence. The longer the silence, the higher the probability that a NAT rebinding happen. But for privacy reasons, many stacks perform a CID rotation after a long silence. It is very likely that many NAT rebinding will also be associated with CID rotation.

We have an ambiguity between two scenarios that present the same symptoms to the peer, yet require a different handling. The best way to solve that ambiguity is to never use path migration, and always treat arrival of a new four tuple as a NAT rebinding, whatever the value of the CID.

**Comment by gloinul** [comment]
I think you made some errors in the table above @huitema. I think an important difference is if the packet contain a Path Challenge or not. And in addition shouldn't the NAT rebinding have "Different 4-tuple"? So I think my version of this table is the following: 

Event | Observation | Verification needed | If verification fails
-- | -- | -- | --
CID rotation | Different CID but matching this path, same 4-tuple | No | Cannot fail
NAT rebinding | Same CID, different 4-tuple | Yes | retain old 4 tuple
NAT rebinding with simultaneous CID rotation | Different CID, different 4-tuple | Yes | retain old 4 tuple, use new CID
Migration | PC + new CID for existing path, different 4-tuple | Yes | retain old 4 tuple, use old CID (per RFC 9000). In case of success, wait for validating frames before using the new 4-tuple
New PATH | PC + CID for new Path ID | Yes | Path failed to be established, PC can be retried with the same CID. 

So I think another aspect here are what would you do if one gets a Migration even if we recommend against it or would consider forbidding it. Protocol violation? And can we really take things to that state considering what RFC 9000 says?

**Comment by huitema** [comment]
If someone attempted a migration, I would treat it the same as a NAT Rebinding.

**Comment by huitema** [comment]
We are replacing the "migration" process of RFC 9000 by the path creation process, yes.

**Comment by huitema** [comment]
I don't want to make any difference based on the content of packets. We also discussed that before, that was one of the proposals before adopting unique ID. Any packet can contain a PATH CHALLENGE at any time. It is actually a pretty good way to implement a "keep alive" process for a path.

**Comment by mirjak** [comment]
So I still don't think there is a problem. If you see a new 4-tuple on an existing path ID, it's a migration (NAT rebinding is always migration). If you want to send on a new 4-tuple that you haven't validated yet, you must validate it. If you receive a path_challange, you should reply to it (on the same 4 tuple). that's it!

**Comment by huitema** [comment]
Based on a discussion with @mirjak, @gloinul and @Yanmei-Liu, I think we could have the following resolution:

1) Add a strong recommendation to use multipath mechanisms for the migration scenarios, because they are much more controlled and deterministic than the basic migration in 9000. The multipath mechanisms allow "make before break", using PATH_AVAILABLE and PATH_BACKUP frames to control where to send traffic, and PATH_ABANDON to cleanly "break" one path after other paths are available.

2) Add some text explaining that we do have some ambiguity in RFC 9000 between the "uncontrolled" NAT Rebinding scenario and the "controlled" migration scenarios. This ambiguity can be resolved using heuristics, but the heuristics will get confused some time. Implementations that do not want to rely on these heuristics can simplify their code by only supporting the NAT Rebinding scenario. This will drop support for scenarios like "prepare a migration, validate the continuity of the 4-tuple, then keep the 4-tuple in standby until the app decides to use it" -- NAT Rebinding only does immediate migration, if the old path is still available, the new attempt is discarded.

**Comment by mirjak** [comment]
Based on the discussion at IETF 121 we will propose a PR to add a field to the PATHS_BLOCKED frame and an error code the PATH_ABANDON frame.

**Comment by mirjak** [comment]
@huitema on your point 2 above: I think this is, if at all, an issue for RFC9000 and not for this draft. Therefore I don't think we should  add any discussion in this draft. Actually I disagree about this problem. I don't think there is ambiguity but instead it was on purpose a decision in RFC9000 to treat these two cases the same. If you decide to not implement migration as specified in RFC9000 for both cases then that's your local decision and migration will fail in some cases. That's okay but has nothing to do with the multipath extension.

**Comment by mirjak** [comment]
@huitema we are ready to merge PR #469. Do you think this would address this issue or do you think we need anymore discussion on your point 2 above?
