### ISSUE TITLE
Clarification on Preferred Address handling

### ISSUE THREAD

**Issue by huitema** [quicwg/multipath#460]
The current draft (version 11) says _"Also, the Path ID for the connection ID specified in the "preferred address" transport parameter is 0. Use of the "preferred address" is considered as a migration event that does not change the Path ID."_ This point is further reinforced in the path management section: _"In particular, if the server uses the preferred_address transport parameter, clients cannot assume that the initial server address and the addresses contained in this parameter can be simultaneously used for multipath (Section 9.6.2 of [QUIC-TRANSPORT])."_

This is questionable, since support of RFC-9000 style "migration" is problematic, as explained in issue #458. With multipath negotiated, "path migration" uses the same code path as "NAT Rebinding", which is a poor fit for preferred address migration. The selected path will eventually depend on the order in which packets are received, which might bring back usage of the original address instead of the preferred address. 

Clients will get a much more reliable result if they proceed in two steps: first establish a new path to the preferred address (typically path id 1), then abandon the initial path (path id 0). This is the "make before break" scenario that should generally be preferred to path migration. But this behavior is gated by two conditions: the server should allow a "max path id" value no lower than 1; and, the server shall provide the client with connection IDs for path 1. Otherwise, the client will have to wait until the server sends a new MAX_PATH_ID and PATH_CONNECTION_ID frames.

We may want to revise the text to explicitly authorize "make before break" behavior, i.e., using path creation instead of path migration for handling the preferred address. If we don't do that, stacks would probably need a special handling of the preferred address, as an exception to the normal code behavior, and that special handling should probably be discussed in the implementation section.

**Comment by mirjak** [comment]
I don't think we need to do anything here as well also allow opening new path before/instead of the preferred address migration. If an endpoint indicated a max path id of 0, it a clear sign it effectively doesn't want to used multipath (yet) and especially for the preferred address might prefer migration. So the only thing we could/should explicitly recommend is that if the max path is larger than 0, then a new path should be used instead of migration for the preferred address.

**Comment by huitema** [comment]
There is a small matter of timing. There will be some time between "max path is larger than 0" and "a CID is available for path=1".

**Comment by mirjak** [comment]
@huitema but that means it's better to treat this as migration and keep using path ID 0, no? Are any chances needed here or can we close the issue?

**Comment by huitema** [comment]
Migration is never better than creation of a new path followed by deletion of the old path -- the path creation allows proper make before break, which RFC 9000 style migration does not. And yes, in that case that means deleting path 0. But given what we have written, we can have server implementations that delay providing CID for path 1 until migration of path 0 to the preferred address is complete. Combine that with a stubborn client that does not do migration, and we have an interop problem.

I guess part of the issue is that I treated the old "migration" code as "creating a path". It does something else, merely validating a 4 tuple. The path creation only happens in RFC 9000 when the client actually migrates a path to a new tuple -- a different concept than what we do with path creation. I don't have time to fix that immediately, but should be able to review it in December.

But then, RFC 9000 migration relies on the concept of "path validating frames". I hoped I could get rid of that.

**Comment by mirjak** [comment]
Okay, I understand the issue in your implementation but I don't think we can or should change anything in the draft.

If we would define the path ID to be 1 for the CID provided by the preferred_address parameter that would mean that we have a dependency between transport parameters where a preferred address can only be used if the initial_max_path_id is set to at least 1. Not sure I like that. Also we should maybe consider to reserve path ID 1 than only for the preferred address to avoid ambiguity but that seems a bit ugly, too.

However,  I don't think we should take on another such design change if there is not really an unsolved problem that needs fixing or otherwise things don't work. I guess this could be still addressed in a separate extension at a later point of time if that is seen as a valuable thing...?

Therefore I still propose that we close this issue for now without any changes.
