### ISSUE TITLE
Sending non-probe packets before path validation complete

### ISSUE THREAD

**Issue by Yanmei-Liu** [quicwg/multipath#50]
As we have 0-RTT transmission in QUIC-TRANSPORT, and path validation brings at lease one round-trip-time delay for data to be sent on the new path, can we add some mechanism to provide anti-amplification limitation and support this scenario?

**Comment by mirjak** [comment]
@Yanmei-Liu do you have a proposal?

**Comment by mirjak** [comment]
Feedback from IETF-113: This proposal needs a more clear use case. If you have a use case, please describe it here!

**Comment by ekinnear** [comment]
In most cases where it would matter, it seems like we can get path validation out of the way ahead of time, before we need a new path. 

If you're trying to bring it up as part of 0-RTT/immediately, the amplification limit means that you potentially cannot send a full initial window of data, but you can still get started on slow start/getting that path up and running at the same time as you do path validation.

Also, shouldn't the packet sizing requirements help push the congestion window larger even if you're not yet using the path for non-probing packets and are just using padding? This is the same mechanism as how you can pre-warm a path for migration without needing to drop back to zero when you switch to the new path.

**Comment by huitema** [comment]
We may want to develop a security section a bit more. The only reason to send data frames immediately is the potential for reflection attacks if a peer can be induced to send data on an invalid path. There are degrees of fear. For example, if the destination address is already validated on another path and this is just the client trying sending from a different interface, then the fear-factor is very low. The only risk is that for some reason the new path will not work, causing retransmissions. The sender implementation may want to take the risk.

On the other hand, if this is a new destination address, the risk of DOSsing some innocent target is substantial, so maybe only send a minimum amount of traffic!

**Comment by kazuho** [comment]
I am coming to the impression that we should just get rid of "probing" state altogether. That's an unnecessary complexity in Multipath.

Of course, path validation is necessary when an endpoint sends packets to a new remote address. However, from the standpoint of security, there is no need to have "probing" state that forbids an endpoint from sending most types of frames.

IIRC, the only reason we have the distinction of probing packets and non-probing packets is because QUIC v1 has only one loss recovery and congestion controller. Because there is one, there has to be signal that indicates to peer the change of the active path (i.e., the path that uses loss recovery and congestion controller) - that is one non-probing packets are used for.

With Multipath QUIC, we have per-path loss recovery and congestion control. Then, why do we have to keep the concept of "probing" and "non-probing" packets and frames at all?

We can just allow any types of frames to be sent even in the packets used to validate a new path, and call it a day.

**Comment by marten-seemann** [comment]
That’s an interesting idea, @kazuho! I like getting rid of the concept of probing and non-probing frames / packets.

It would probably make sense to recommend including a PATH_STATUS frame in the packet containing the PATH_CHALLENGE. Alternatively, we could also define a default status that applies if no PATH_STATUS has been sent yet (there’s a discussion about that in #218).

At the very least, whatever we come up with needs to support the following two common scenarios:
1. Establishing a “backup path”: This is very common for mobile devices that might want to validate a cellular path even when they’re connected to a strong WiFi. In that case, there needs to be a way to make sure that a clear preference for the WiFi path can be expressed.
2. The “parking lot” case, i.e. a mobile device moving away from a WiFi, and wishing to switch to the cellular path asap. In that case, the client would want to communicate a preference for the new path, as soon as this new path is available and validated.

If I understand correctly, both scenarios are supported by using PATH_STATUS frames.

**Comment by mirjak** [comment]
Yes, I also like this idea. If congestion control was the only reason for this differentiation, we don't need it anymore. And while it is a divergence from RFC9000, it probably rather a simplification.

**Comment by huitema** [comment]
I like the suggestion of inserting a PATH_STATUS frame in the packet carrying the PATH_CHALLENGE. That's one of the areas in which RFC9000 is a bit weak. And I generally prefer having explicit statements like "consider this pat available" than implict statement like "this path will be available if the client sends a frame of the right color".
