### ISSUE TITLE
 Congestion Control, RTT measurements and PMTU discovery should be per-path 

### ISSUE THREAD

**Issue by obonaventure** [quicwg/multipath#89]
The sentence above is part of the introduction, but the should is misleading for congestion control at least (we have a MUST for per-path congestion control later).

I would suggest to split the above sentence in two parts:
-  Congestion Control must be performed per-path 
-  Path MTU should be performed per path

We should probably list somewhere in the document the state that must/should be maintained on a per-path basis and the state that is related to the connection. This could clarify some of the mechanisms.

Concerning PathMTU, I would suggest to stay with a should and not a must since an implementation could simply track the minimum MTU among the different paths without maintaining per-path MTU. Such an implementation would work and if the MTUs do not differ significantly, it would probably be simpler than an implementation than maintains per-path MTU and needs to adjust the packets based on the path where each packet is sent.

Concerning RTT, we discuss the problem of measuring the RTT later with the packet number spaces discussion. Furthermore, some congestion control schemes need an accurate per-path RTT while others do not strictly require rtt estimations.

**Comment by mirjak** [comment]
@obonaventure this "should" in the intro was not meant to be normative. However, I anyway created PR #98 to clarify. 

However, I didn't address your point about having a list of all state. Do we really need that? If so, where does that below? A new section somewhere? Can you provide such a list or create a PR? Or should we open a new separate issue for that?

**Comment by huitema** [comment]
I agree that specifying PMTUD per path is a good idea. We do have a slight ambiguity, because the draft uses the overlapping notions of "path" and "number space", with the number space tied to the DCID of packets. The DCID may change over time for privacy reasons, or because the server wants to retire old CIDs tied to a previous configuration of the load balancer. In these cases, there is no need to restart PMTUD or reset congestion control.
