### ISSUE TITLE
A path can be active even if it does not carry packets in both directions since ACKs can be returned on another path

### ISSUE THREAD

**Issue by obonaventure** [quicwg/multipath#90]
In 3.2.3, we have the following paragraph:

     When more than one path is available, servers shall monitor the arrival of non-probing packets on the available paths. Servers   
     SHOULD stop sending traffic on paths through where no non-probing packet was received in the last 3 path RTTs, but MAY
     ignore that rule if it would disqualify all available paths. To avoid idle timeout of a path, endpoints can send ack-eliciting packets
     such as packets containing PING frames Section 19.2 of [QUIC-TRANSPORT] on that path to keep it alive. Sending periodic
     PING frames also helps prevent middlebox timeout, as discussed in Section 10.1.2 of [QUIC-TRANSPORT].

This paragraph implicitly indicates that we consider a path to be active if we send and receive packets on this path. This definition works well for MPTCP where each data packet triggers an ACK on the same path. In MPQUIC, a server could have two paths that it uses to send data. However, the client might decide to always send the ACKs on only one path (e.g. the lowest delay one). In this case, the two paths are clearly active, but the server could consider the higher delay path to be inactive since it does not receive packets over this path. It could send PING frames to trigger data packets, but then it would need to send one PING every 3 RTT, which seams excessive. 

I would suggest to rewrite the text as follows (I removed Server, because I think the recommendation should be generic):

     When more than one path is available, hosts shall monitor both the arrival of non-probing packets and the acknowledgements 
     for the packets sent over each path. Hosts SHOULD stop sending traffic on paths whether either: (a) no non-probing packet
     was received in the last 3 path RTT or (b) no non-probing packet sent over this path was acknowledged during the last 3 path 
     RTT, but MAY ignore that rule if it would disqualify all available paths. To avoid idle timeout of a path, endpoints can send 
     ack-eliciting packets such as packets containing PING frames Section 19.2 of [QUIC-TRANSPORT] on that path to keep 
     it alive. Sending periodic PING frames also helps prevent middlebox timeout, as discussed in Section 10.1.2 of [QUIC-TRANSPORT].

**Comment by yfmascgy** [comment]
The word "either" means that STOP sending becomes true If either (a) is true or (b) is true. If I understand correctly, the actual meaning is to use the word "both" here, instead. So stop sending if both (a) no non-probing packets received and (b) no packets was acknowledged.

**Comment by mirjak** [comment]
Yes, I think this is a good clarification and yes "either" might be confusing here.

**Comment by huitema** [comment]
I commented on the PR. I don't like the idea that receivers would have to stop acknowledging packets in order to signal preference to not use a path. We need to think that a little more.

**Comment by huitema** [comment]
So we have a choice:

* either say that nodes should regularly send non-probing packets over the path that they want to keep using,
* or if we don't want that, accept the idea that acks on other paths show continuity, and require "abandon path" to terminate a path that is otherwise working, acknowledges packets, etc..

**Comment by mirjak** [comment]
Yes, I think the second option is what we are aiming for with the new text. Stopping ack'ing packets to stop someone sending on a path is wrong and is something you should never do. If you receive a packet successfully you should ack it (also because that would otherwise confuse congestion control). But we have the abandon frame exactly for that case.

However, it also seems wrong to me to require sending acks on the same path taen the data is received. So if you decide to always only send ack on one path and all payload data flows into one direction only over multiple paths, the current text would require you to send potentially unnecessary ping packets over each non-ack'ing paths or you would end up closing those paths which also is wrong as everything seems to work fine.

So the question is really is, do we want to require pings in this scenario (payload traffic over multiple paths but acks only on one path) in order to ensure that all paths are usable bidirectionally? I think that's unnecessary overhead and believe Olivier's proposed addition is the correct thing to do.

**Comment by huitema** [comment]
I can look at what I implemented in picoquic:

* If there is no traffic in either direction for the idle period, the path is automatically abandoned. If traffic is sent and acked, or traffic is received, the path is not considered idle. This is pretty much what Olivier proposed.
* If there is a "timer loss", and if there is an alternate, the path is put in a low priority list. The node will send ping and try get an ack. If no ack is received after N trials, the path is abandoned.
* If "abandon path" frame is received, the path is abandoned.

**Comment by mirjak** [comment]
I marked this issue as editorial as we have an editorial PR for it. However, I open a new issue for the per path idle timeout discussion (#95).

Do we need another issue to clarify path closure or sending of keep-alive traffic? However this might be covered in other parts of the draft already...?
